[colors]

[colors.normal]
black = "#222222"
red = "#db475f"
green = "#5f953c"
yellow = "#ac7925"
blue = "#3d85dc"
magenta = "#b250d9"
cyan = "#2a9595"
white = "#b9b9b9"

[colors.bright]
black   = "#463a3a"
red     = "#ff8297"
green   = "#c8e292"
yellow  = "#fcd675"
blue    = "#f8a788"
magenta = "#c36ee7"
cyan    = "#9bf1e1"
white   = "#f1e5e7"

[colors.cursor]
cursor = '#c3b7b8'
text = '#c3b7b8'

[colors.primary]
background = "#080808"
foreground = "#e2e2e2"

[colors.selection]
background = "#080808"
text = '#e6d9db'
