[colors]
[colors.primary]
background = "#080808"
foreground = "#e2e2e2"

[colors.normal]
black   = '#090618'
red     = '#c34043'
green   = '#76946a'
yellow  = '#c0a36e'
blue    = '#7e9cd8'
magenta = "#b250d9"
cyan    = '#6a9589'
white   = '#c8c093'

[colors.bright]
black   = '#727169'
red     = '#e82424'
green   = '#98bb6c'
yellow  = '#e6c384'
blue    = '#7fb4ca'
magenta = "#c36ee7"
cyan    = '#7aa89f'
white   = '#dcd7ba'

[colors.selection]
background = "#080808"
foreground = "#e2e2e2"

[[colors.indexed_colors]]
index = 16
color = '#ffa066'

[[colors.indexed_colors]]
index = 17
color = '#ff5d62'
